version: "1.0"
services:
  mysqldb:
    container_name: mysql2
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    networks:
      springboot-mysql-network:

  spring-boot-restful-webservices:
    container_name: spring-boot-restful-webservices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-network:
    restart: on-failure


networks:
  springboot-mysql-network:
