GET http://localhost:8080/api/users
Accept: application/json

###
GET http://localhost:8080/api/users/4
accept: application/json

###
POST http://localhost:8080/api/users/add
Content-Type: application/json

{
  "firstName": "Jonttu",
  "lastName": "Sakea",
  "email": "risto@sakea.com"
}
###
PUT http://localhost:8080/api/users/update/5
Content-Type: application/json

{
  "firstName": "Jihaa",
  "lastName": "TheMonke",
  "email": "ihaa@donkey.com"
}

###
DELETE http://localhost:8080/api/users/delete/6

###
#Changes thes logging level of net.javaguides. Didn't work
POST http://localhost:8080/actuator/loggers/net.javaguides
Content-Type: application/json

{ "effectiveLevel":"3" }

###
POST http://localhost:8080/actuator/shutdown

