GET http://localhost:8080/api/users
Accept: application/json

###
GET http://localhost:8080/api/users/4
accept: application/json

###
POST http://localhost:8080/api/users/add
Content-Type: application/json

{
  "firstName": "Nasu",
  "lastName": "Kenguru",
  "email": "nasu@kenguru.com"
}
###
PUT http://localhost:8080/api/users/update/5
Content-Type: application/json

{
  "firstName": "Nasu",
  "lastName": "Kenguru",
  "email": "nasu@kangaroo.com"
}

###
DELETE http://localhost:8080/api/users/delete/2

